name: Generate Changelog

on: [ push ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create CHANGELOG.md
        id: change_log
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: c91dcd70f372606c61427092930400e1c68b0673
#          git-message: Update Changelog
          output-file: false



