name: Generate Changelog

on: [ push ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create CHANGELOG.md
        id: change_log
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: ${{ secrets.github_token }}
#          git-message: Update Changelog
#          output-file: false



