name: Create release

on:
  push:
    branches: [ dev ]
#    tags:
#      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Github Release create, update, and upload assets
        uses: meeDamian/github-release@v2.0.1
        with:
          tag: v-dev
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          allow_override: true
          body: |
            Changelog for ${{ steps.get_version.outputs.VERSION }}
            Automatically create release and upload JAR
          files: build/libs/actions-test-${{ steps.get_version.outputs.VERSION }}.jar
          gzip: folders
